<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="oramds:/apps/FusionOrderDemoShared/services/oracle/fodemo/storefront/store/service/common/serviceinterface/StoreFrontService.wsdl"/>
      <rootElement name="getOrderInfoVOSDOResponse" namespace="www.globalcompany.example.com/types/"/>
    </source>
    <source type="XSD">
      <schema location="oramds:/apps/FusionOrderDemoShared/services/orderbooking/OrderProcessor.xsd"/>
      <rootElement name="updateOrderStatus" namespace="http://www.globalcompany.example.com/ns/OrderBookingService"/>
      <param name="initial.payload" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="oramds:/apps/FusionOrderDemoShared/services/oracle/fodemo/storefront/store/service/common/serviceinterface/StoreFrontService.wsdl"/>
      <rootElement name="updateOrderInfoVOSDO" namespace="www.globalcompany.example.com/types/"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.0.0(build 080902.2000.1881) AT [FRI OCT 10 19:48:08 PDT 2008]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xpath20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:types="www.globalcompany.example.com/types/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:errors="http://xmlns.oracle.com/adf/svc/errors/"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ns1="commonj.sdo/xml"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns2="http://xmlns.oracle.com/adf/svc/types/"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:tns="www.globalcompany.example.com"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.GetRequestHeaderExtnFunction"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns3="commonj.sdo/java"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns4="/oracle/fodemo/storefront/store/queries/common/"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="commonj.sdo"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns5="http://www.globalcompany.example.com/ns/OrderBookingService"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl types soap wsdl errors ns1 ns2 tns ns3 ns4 ns0 xsd ns5 bpws xpath20 ora oraext dvm hwf mhdr med ids xdk xref ldap">
  <xsl:param name="initial.payload"/>
  <xsl:template match="/">
    <types:updateOrderInfoVOSDO>
      <types:orderInfoVO1>
        <ns4:OrderId>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:OrderId/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:OrderId"/>
        </ns4:OrderId>
        <ns4:OrderDate>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:OrderDate"/>
        </ns4:OrderDate>
        <ns4:OrderShippedDate>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:OrderShippedDate/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:OrderShippedDate"/>
        </ns4:OrderShippedDate>
        <ns4:OrderStatusCode>
          <xsl:value-of select="$initial.payload/ns5:updateOrderStatus/ns5:orderStatus"/>
        </ns4:OrderStatusCode>
        <ns4:OrderTotal>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:OrderTotal"/>
        </ns4:OrderTotal>
        <ns4:CustomerId>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:CustomerId"/>
        </ns4:CustomerId>
        <ns4:ShipToName>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:ShipToName/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:ShipToName"/>
        </ns4:ShipToName>
        <ns4:ShipToPhoneNumber>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:ShipToPhoneNumber/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:ShipToPhoneNumber"/>
        </ns4:ShipToPhoneNumber>
        <ns4:AddressId>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:AddressId/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:AddressId"/>
        </ns4:AddressId>
        <ns4:Address1>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:Address1"/>
        </ns4:Address1>
        <ns4:Address2>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:Address2/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:Address2"/>
        </ns4:Address2>
        <ns4:City>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:City"/>
        </ns4:City>
        <ns4:PostalCode>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:PostalCode/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:PostalCode"/>
        </ns4:PostalCode>
        <ns4:StateProvince>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:StateProvince"/>
        </ns4:StateProvince>
        <ns4:CountryId>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:CountryId"/>
        </ns4:CountryId>
        <ns4:PaymentOptionId>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:PaymentOptionId/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:PaymentOptionId"/>
        </ns4:PaymentOptionId>
        <ns4:BillingAddressId>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:BillingAddressId/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:BillingAddressId"/>
        </ns4:BillingAddressId>
        <ns4:AccountNumber>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:AccountNumber"/>
        </ns4:AccountNumber>
        <ns4:CardTypeCode>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:CardTypeCode/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:CardTypeCode"/>
        </ns4:CardTypeCode>
        <ns4:ExpireDate>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:ExpireDate/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:ExpireDate"/>
        </ns4:ExpireDate>
        <ns4:CheckDigits>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:CheckDigits/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:CheckDigits"/>
        </ns4:CheckDigits>
        <ns4:RoutingIdentifier>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:RoutingIdentifier/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:RoutingIdentifier"/>
        </ns4:RoutingIdentifier>
        <ns4:InstitutionName>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:InstitutionName/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:InstitutionName"/>
        </ns4:InstitutionName>
        <ns4:ShipToAddressId>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:ShipToAddressId"/>
        </ns4:ShipToAddressId>
        <ns4:ObjectVersionId>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:ObjectVersionId"/>
        </ns4:ObjectVersionId>
        <ns4:ShippingOptionId>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:ShippingOptionId"/>
        </ns4:ShippingOptionId>
        <ns4:ObjectVersionId1>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:ObjectVersionId1"/>
        </ns4:ObjectVersionId1>
        <ns4:FreeShippingFlag>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:FreeShippingFlag"/>
        </ns4:FreeShippingFlag>
        <ns4:ObjectVersionId2>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:ObjectVersionId2"/>
        </ns4:ObjectVersionId2>
        <ns4:CustomerCollectFlag>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:CustomerCollectFlag"/>
        </ns4:CustomerCollectFlag>
        <ns4:GiftwrapFlag>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:GiftwrapFlag"/>
        </ns4:GiftwrapFlag>
        <ns4:PaymentOptionId1>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:PaymentOptionId1/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/types:getOrderInfoVOSDOResponse/types:result/ns4:PaymentOptionId1"/>
        </ns4:PaymentOptionId1>
        <xsl:for-each select="/types:getOrderInfoVOSDOResponse/types:result/ns4:OrderItemsInfoVO">
          <ns4:OrderItemsInfoVO>
            <ns4:OrderId>
              <xsl:value-of select="ns4:OrderId"/>
            </ns4:OrderId>
            <ns4:LineItemId>
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="ns4:LineItemId/@xsi:nil"/>
              </xsl:attribute>
              <xsl:value-of select="ns4:LineItemId"/>
            </ns4:LineItemId>
            <ns4:ProductId>
              <xsl:value-of select="ns4:ProductId"/>
            </ns4:ProductId>
            <ns4:Quantity>
              <xsl:value-of select="ns4:Quantity"/>
            </ns4:Quantity>
            <ns4:UnitPrice>
              <xsl:value-of select="ns4:UnitPrice"/>
            </ns4:UnitPrice>
            <ns4:ProductName>
              <xsl:value-of select="ns4:ProductName"/>
            </ns4:ProductName>
            <ns4:SupplierName>
              <xsl:value-of select="ns4:SupplierName"/>
            </ns4:SupplierName>
            <ns4:ProductId1>
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="ns4:ProductId1/@xsi:nil"/>
              </xsl:attribute>
              <xsl:value-of select="ns4:ProductId1"/>
            </ns4:ProductId1>
          </ns4:OrderItemsInfoVO>
        </xsl:for-each>
      </types:orderInfoVO1>
    </types:updateOrderInfoVOSDO>
  </xsl:template>
</xsl:stylesheet>
