<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../PartnerSupplierMediator.wsdl"/>
      <rootElement name="orderInfoVOSDO" namespace="/oracle/fodemo/storefront/store/queries/common/"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="oramds:/apps/FusionOrderDemoShared/services/partnersupplier/PartnerSupplierComposite.wsdl"/>
      <rootElement name="WarehouseProcessRequest" namespace="http://www.partnersupplier.example.com/ns/warehouse"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.0.0(build 080902.2000.1881) AT [TUE SEP 16 22:33:12 PDT 2008]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xpath20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:tns="http://xmlns.oracle.com/WebLogicFusionOrderDemo/OrderBookingComposite/PartnerSupplierMediator"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:cb1="http://www.globalcompany.example.com/ns/InternalWarehouse"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns3="http://xmlns.oracle.com/adf/svc/errors/"
                xmlns:client="http://www.partnersupplier.example.com/ns/warehouse"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ns1="commonj.sdo/xml"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns2="http://xmlns.oracle.com/adf/svc/types/"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.GetRequestHeaderExtnFunction"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns4="commonj.sdo/java"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:inp1="/oracle/fodemo/storefront/store/queries/common/"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="commonj.sdo"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns cb1 wsdl ns3 ns1 ns2 ns4 inp1 ns0 xsd plnk client bpws xpath20 ora oraext dvm hwf mhdr med ids xdk xref ldap">
  <xsl:template match="/">
    <client:WarehouseProcessRequest>
      <client:orderTotal>
        <xsl:value-of select="/inp1:orderInfoVOSDO/inp1:OrderTotal"/>
      </client:orderTotal>
      <xsl:for-each select="/inp1:orderInfoVOSDO/inp1:OrderItemsInfoVO">
        <client:orderItems>
          <client:price>
            <xsl:value-of select="inp1:UnitPrice"/>
          </client:price>
          <client:quantity>
            <xsl:value-of select="inp1:Quantity"/>
          </client:quantity>
          <client:productId>
            <xsl:value-of select="inp1:ProductId"/>
          </client:productId>
        </client:orderItems>
      </xsl:for-each>
    </client:WarehouseProcessRequest>
  </xsl:template>
</xsl:stylesheet>
