<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../UpdateOrderStatus.wsdl"/>
      <rootElement name="updateOrderStatus" namespace="http://www.globalcompany.example.com/ns/OrderBookingService"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="oramds:/apps/FusionOrderDemoShared/services/orderbooking/OrderProcessor.xsd"/>
      <rootElement name="updateOrderStatus" namespace="http://www.globalcompany.example.com/ns/OrderBookingService"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.0.0(build 080902.2000.1881) AT [FRI OCT 10 19:51:31 PDT 2008]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xpath20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:tns="http://xmlns.oracle.com/WebLogicFusionOrderDemo/OrderBookingComposite/UpdateOrderStatus"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.GetRequestHeaderExtnFunction"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:inp1="http://www.globalcompany.example.com/ns/OrderBookingService"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns xsd wsdl inp1 xpath20 bpws oraext dvm hwf med mhdr ids xdk xref ora ldap">
  <xsl:template match="/">
    <inp1:updateOrderStatus>
      <inp1:orderId>
        <xsl:value-of select="/inp1:updateOrderStatus/inp1:orderId"/>
      </inp1:orderId>
      <inp1:orderStatus>
        <xsl:value-of select="/inp1:updateOrderStatus/inp1:orderStatus"/>
      </inp1:orderStatus>
    </inp1:updateOrderStatus>
  </xsl:template>
</xsl:stylesheet>
