<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="oramds:/apps/FusionOrderDemoShared/services/partnersupplier/PartnerSupplierComposite.wsdl"/>
      <rootElement name="WarehouseProcessResponse" namespace="http://www.partnersupplier.example.com/ns/warehouse"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../PartnerSupplierMediator.wsdl"/>
      <rootElement name="WarehouseResponse" namespace="http://www.globalcompany.example.com/ns/InternalWarehouse"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.0.0(build 080902.2000.1881) AT [FRI SEP 12 15:38:38 PDT 2008]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xpath20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:client="http://www.partnersupplier.example.com/ns/warehouse"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.GetRequestHeaderExtnFunction"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns1="http://www.globalcompany.example.com/ns/InternalWarehouse"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl client plnk xsd wsdl ns1 xpath20 bpws oraext dvm hwf med mhdr ids xdk xref ora ldap">
  <xsl:template match="/">
    <ns1:WarehouseResponse>
      <ns1:warehouse>
        <xsl:text disable-output-escaping="no">
          PartnerWarehouse
        </xsl:text>
      </ns1:warehouse>
      <ns1:deliveryDate>
        <xsl:value-of select="/client:WarehouseProcessResponse/client:deliveryDate"/>
      </ns1:deliveryDate>
      <ns1:orderTotal>
        <xsl:value-of select="/client:WarehouseProcessResponse/client:orderTotal"/>
      </ns1:orderTotal>
    </ns1:WarehouseResponse>
  </xsl:template>
</xsl:stylesheet>
