<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="FulfillOrder"
     targetNamespace="http://xmlns.oracle.com/WebLogicFusionOrderDemo/OrderBookingComposite/FulfillOrder"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:inp1="/oracle/fodemo/storefront/store/queries/common/"
     xmlns:tns="http://xmlns.oracle.com/WebLogicFusionOrderDemo/OrderBookingComposite/FulfillOrder"
    >
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="/oracle/fodemo/storefront/store/queries/common/" schemaLocation="oramds:/apps/FusionOrderDemoShared/services/oracle/fodemo/storefront/store/queries/common/OrderInfoVOSDO.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="request" element="inp1:orderInfoVOSDO"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="execute">
            <wsdl:input message="tns:requestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
