<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="UpdateOrderStatus"
     targetNamespace="http://xmlns.oracle.com/WebLogicFusionOrderDemo/OrderBookingComposite/UpdateOrderStatus"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:inp1="http://www.globalcompany.example.com/ns/OrderBookingService"
     xmlns:tns="http://xmlns.oracle.com/WebLogicFusionOrderDemo/OrderBookingComposite/UpdateOrderStatus"
    >
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://www.globalcompany.example.com/ns/OrderBookingService" schemaLocation="oramds:/apps/FusionOrderDemoShared/services/orderbooking/OrderProcessor.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="request" element="inp1:updateOrderStatus"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="execute">
            <wsdl:input message="tns:requestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
