package writequoterequest.partnersuppliercomposite.weblogicfusionorderdemo.file.adapter.pcbpel.com.oracle.xmlns;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 090723.1820.59489)

@WebService(targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/file/WebLogicFusionOrderDemo/PartnerSupplierComposite/WriteQuoteRequest",
  name="Write_ptt")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso(
  { writequoterequest.partnersuppliercomposite.weblogicfusionorderdemo.file.adapter.pcbpel.com.oracle.xmlns.ObjectFactory.class })
public interface Write_ptt
{
  @WebMethod(operationName="Write")
  @Action(input="http://xmlns.oracle.com/pcbpel/adapter/file/WebLogicFusionOrderDemo/PartnerSupplierComposite/WriteQuoteRequest/Write_ptt/Write")
  @Oneway
  public void write(@WebParam(partName="body", name="quoteRequest", targetNamespace = "http://TargetNamespace.com/writeProducts")
    writequoterequest.partnersuppliercomposite.weblogicfusionorderdemo.file.adapter.pcbpel.com.oracle.xmlns.QuoteRequest body);
}
