<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="../../OrderSensorActionSensorAction_1.xsd"/>
      <rootElement name="actionData" namespace="http://xmlns.oracle.com/bpel/sensor"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../Demos/Fusion%20Order%20Demo/Order.wsdl"/>
      <rootElement name="_OrderCollection" namespace="http://xmlns.oracle.com/bam"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.0.0(build 081209.0200.2271) AT [TUE DEC 09 11:52:08 PST 2008]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xpath20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:ns5="http://xmlns.oracle.com/bam"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns6="www.globalcompany.example.com/types/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns3="http://xmlns.oracle.com/adf/svc/errors/"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:tns="http://xmlns.oracle.com/bpel/sensor"
                xmlns:ns1="commonj.sdo/xml"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns2="http://xmlns.oracle.com/adf/svc/types/"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.GetRequestHeaderExtnFunction"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns4="commonj.sdo/java"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:sensor="/oracle/fodemo/storefront/store/queries/common/"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd"
                xmlns:ns0="commonj.sdo"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns3 tns ns1 ns2 ns4 sensor nxsd ns0 xsd ns5 xsi bpws xpath20 ora socket oraext dvm hwf mhdr med ids xdk xref ldap">
  <xsl:template match="/">
    <ns5:_OrderCollection>
      <ns5:_Order>
        <ns5:_ECID>
          <xsl:value-of select="/tns:actionData/tns:header/tns:compositeInstanceId"/>
        </ns5:_ECID>
        <ns5:_OrderID>
          <xsl:value-of select="/tns:actionData/tns:payload/tns:variableData/tns:data/sensor:orderInfoVOSDO/sensor:OrderId"/>
        </ns5:_OrderID>
        <ns5:_CustomerID>
          <xsl:value-of select="/tns:actionData/tns:payload/tns:variableData/tns:data/sensor:orderInfoVOSDO/sensor:CustomerId"/>
        </ns5:_CustomerID>
        <ns5:_OrderDate>
          <xsl:value-of select="/tns:actionData/tns:payload/tns:variableData/tns:data/sensor:orderInfoVOSDO/sensor:OrderDate"/>
        </ns5:_OrderDate>
        <ns5:_OrderStatus>
          <xsl:value-of select="/tns:actionData/tns:payload/tns:variableData/tns:data/sensor:orderInfoVOSDO/sensor:OrderStatusCode"/>
        </ns5:_OrderStatus>
        <ns5:_OrderPrice>
          <xsl:value-of select="/tns:actionData/tns:payload/tns:variableData/tns:data/sensor:orderInfoVOSDO/sensor:OrderTotal"/>
        </ns5:_OrderPrice>
      </ns5:_Order>
    </ns5:_OrderCollection>
  </xsl:template>
</xsl:stylesheet>
