package com.example.globalcompany.ccauth.test;

import com.example.globalcompany.ccauth.types.AuthInformation;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 100209.2058.51013)

public class CreditAuthorizationPortClient
{
  @WebServiceRef
  private static CreditAuthorizationService creditAuthorizationService;

  private static final QName SVC_QN =
      new QName("http://www.globalcompany.example.com/ns/CreditAuthorizationService",
                "CreditAuthorizationService");
  private static final String SVC_URI = 
      "WebServices_WebLogicFusionOrderDemo_CreditCardAuthorization/CreditAuthorizationPort?wsdl";

  public static void main(String [] args) throws Exception
  {
    String httpEndpoint = "http://localhost:8001";
    if (args != null && args.length > 0)
        httpEndpoint = args[0];
    
    URL baseUrl = CreditAuthorizationService.class.getResource(".");
    URL wsdlLocationURL =
      new URL(baseUrl, httpEndpoint + "/" + SVC_URI);    
    System.out.println("wsdl location: " + wsdlLocationURL);
    creditAuthorizationService = 
        new CreditAuthorizationService(wsdlLocationURL, SVC_QN);
    CreditAuthorizationPort creditAuthorizationPort = 
        creditAuthorizationService.getCreditAuthorizationPort();
    
    AuthInformation authorizationInfo =
        new AuthInformation();
    authorizationInfo.setCCNumber("4321");
    authorizationInfo.setCCType("AMEX");
    
    System.out.println("Status: " + 
        creditAuthorizationPort.authorizeCredit(authorizationInfo));
  }
}
