package com.example.globalcompany.ccauth.test;

import com.example.globalcompany.ccauth.types.AuthInformation;
import com.example.globalcompany.ccauth.types.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 100209.2058.51013)

@WebService(wsdlLocation="http://130.35.103.126:8888/FODServices-CCAuthorizationService-context-root/CreditAuthorizationPort?wsdl",
  targetNamespace="http://www.globalcompany.example.com/ns/CreditAuthorizationService",
  name="CreditAuthorizationPort")
@XmlSeeAlso(
  { ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface CreditAuthorizationPort
{
  @WebMethod(operationName="AuthorizeCredit", action="http://www.globalcompany.example.com/ns/CreditAuthorizationService/AuthorizeCredit")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://www.globalcompany.example.com/ns/CreditAuthorizationService/AuthorizeCredit", fault =
      { @FaultAction(value="http://www.globalcompany.example.com/ns/CreditAuthorizationService/CreditAuthorizationPort/AuthorizeCredit/Fault/InvalidCredit",
          className=com.example.globalcompany.ccauth.CreditAuthorizationFaultMessage.class) },
    output="http://www.globalcompany.example.com/ns/CreditAuthorizationService/CreditAuthorizationPort/AuthorizeCreditResponse")
  @WebResult(targetNamespace="http://www.globalcompany.example.com/ns/CCAuthorizationService",
    partName="status", name="status")
  public String authorizeCredit(@WebParam(targetNamespace="http://www.globalcompany.example.com/ns/CCAuthorizationService",
      partName="Authorization", name="AuthInformation")
    AuthInformation Authorization)
    throws com.example.globalcompany.ccauth.CreditAuthorizationFaultMessage;
}
